### ISSUE TITLE
remove shadow properties and handle directly

### ISSUE THREAD

**Issue by jjochen** [jjochen/JJFloatingActionButton#118]

**Comment by jjochen** [comment]
clean up all unnecessary properties

**Comment by arshadsk5** [comment]
code please

**Comment by jjochen** [comment]
https://github.com/jjochen/JJFloatingActionButton/blob/dfbaa82faf064a7706ddd5abb359244eaa606a91/Example/JJFloatingActionButton/ConfigurationExampleViewController.swift#L73
https://github.com/jjochen/JJFloatingActionButton/blob/dfbaa82faf064a7706ddd5abb359244eaa606a91/Example/JJFloatingActionButton/ConfigurationExampleViewController.swift#L58
