### ISSUE TITLE
View inset for bottom and trailing separately

### ISSUE THREAD

**Issue by rajtharan-g** [jjochen/JJFloatingActionButton#144]
Hi @jjochen ,

We are able to specify the inset with which the floating button should be placed like below.
```
actionButton.display(inViewController: self, viewInset: 30)
```
![30x30](https://user-images.githubusercontent.com/23209069/41336089-c4f367e2-6f08-11e8-8bb1-1ada8217b68a.png)
Here in above image, the inset with which button is placed is kept at 15 its from the right and 15 its from the bottom. 

What if we need to place at a position of 30 pts from the right and 60 pts from the bottom. I need to have something like below.
![30x60](https://user-images.githubusercontent.com/23209069/41336105-d0124f9e-6f08-11e8-8108-d9070ec342d6.png)

**Comment by jjochen** [comment]
Hey @rajtharan-g,

you can use layout constraints like with any other view.

`display(inViewController:)` doesn't do anything but `addSubview` and define some layout constrains.
See [here](https://github.com/jjochen/JJFloatingActionButton/blob/c7304271d8e8a068e4efae34830d76c2eb58a1f6/Sources/JJFloatingActionButton%2BPlacement.swift#L93) and [here](https://github.com/jjochen/JJFloatingActionButton/blob/c7304271d8e8a068e4efae34830d76c2eb58a1f6/Sources/JJFloatingActionButton%2BPlacement.swift#L38).

If you want to use layout constraints you should remove `display(inViewController:)` and use `addSubview` plus whatever constraints you want instead. 

In any case, it probably makes sense to improve `display(inViewController:)` some more. I will do it as soon as I find some time 😉
