### ISSUE TITLE
Direction of bubbles

### ISSUE THREAD

**Issue by joemerritt** [jjochen/JJFloatingActionButton#149]
Hi, Is there a way to have the bubbles go downwards instead of upwards?

Cheers

**Comment by jjochen** [comment]
This is already possible but it probably make sense to simplify this.

```
        let configuration = JJItemAnimationConfiguration()
        configuration.itemLayout = JJItemLayout { items, actionButton in
            var previousItem: JJActionItem?
            for item in items {
                let previousView = previousItem ?? actionButton
                item.topAnchor.constraint(equalTo: previousView.bottomAnchor, constant: 14).isActive = true
                item.circleView.centerXAnchor.constraint(equalTo: actionButton.centerXAnchor).isActive = true
                previousItem = item
            }
        }
        actionButton.itemAnimationConfiguration = configuration
```

For a full example see here (still on a separate branch): 
https://github.com/jjochen/JJFloatingActionButton/blob/feature/better_downwards_support/Example/JJFloatingActionButton/DownwardsExampleViewController.swift#L34-L44

**Comment by jjochen** [comment]
@joemerritt hope that answers your question. I will close this issue, open it again if there is anything unclear.
