### ISSUE TITLE
Floating button is not visible

### ISSUE THREAD

**Issue by arshadsk5** [jjochen/JJFloatingActionButton#150]
I have tableview in a view controller , in which floating button is not visible please help me. thanks in advance

**Comment by jjochen** [comment]
Could you please provide some code to look at? Otherwise it's hard to know what happened.

**Comment by arshadsk5** [comment]
func floatingBtnSetup(){
        let actionButton = JJFloatingActionButton()
        
        actionButton.itemSizeRatio = 0.5
        actionButton.buttonColor = Utilities.colorWithHexString(hex: themeColor)
        actionButton.addItem(title: "", image: #imageLiteral(resourceName: "icon_filter")) { (item) in
            print("open filter")
            
            self.openPopOver()
        }
        
        view.addSubview(actionButton)
        actionButton.translatesAutoresizingMaskIntoConstraints = false
        actionButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -16).isActive = true
        actionButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -16).isActive = true
        
        //actionButton.display(inViewController: self)
    }

**Comment by jjochen** [comment]
Is the view controller a `UITableViewController` or just a `UIViewController` with a `UITableView`?

**Comment by arshadsk5** [comment]
Yes i am using UIViewcontroller with tableview inside it, but still i cannot see the floating button.

 @IBOutlet weak var tblView: UITableView!

**Comment by arshadsk5** [comment]
I have a main UIViewcontroller , under that i have sub UIViewcontroller as container, under that sub UIViewcontroller i have tableview outlet. I wanted to show floating button under sub UIViewcontroller which is a container view. Please help.

**Comment by jjochen** [comment]
There are couple of things you could try:

★ Make sure the button is on the top of the view hierarchy. 

★ Replace the action button with a simple `UIView` (don't forget to set the background color) and see if that shows up. 

★ You could have a look at the view hierarchy. Press this Button when the App is running on the simulator:
![screen shot 2018-08-17 at 09 33 02](https://user-images.githubusercontent.com/1793434/44255262-bf21ce00-a205-11e8-830d-76d0994a8146.png)
![screen shot 2018-08-17 at 09 33 46](https://user-images.githubusercontent.com/1793434/44255284-cd6fea00-a205-11e8-9867-b70afe3c0834.png)

**Comment by arshadsk5** [comment]
No i cannot see the button in view hierarchy, can i add a button in
storyboard with floating button custom class ?



<http://goog_1712691528>
*Regards,* <http://goog_1712691528>
*Sk . Arshad* <http://goog_1712691528>
*+91 9553323751.*

**Comment by jjochen** [comment]
@arshadsk5 yes you can. Check out the [example](https://github.com/jjochen/JJFloatingActionButton/tree/master/Example/JJFloatingActionButton) for guidance.

What happened when you replaced the action button with a simple UIView? Were you able to see the view?

**Comment by jjochen** [comment]
If you replace the view with a simple `UIView` and you are still not able to see it, the issue is unrelated to `JJFloatingActionButton`, or am I missing something?

**Comment by arshadsk5** [comment]
Actually what happened is, i am using SlidingContainerView ie., similar to  MDTabBar where we can slide two or more viewcontrollers. I want to show the floating button under one of the sliding viewcontrollers which is added to container of the main viewcontroller. So it is not visible, but i add the floating button to the main viewcontroller in which we have multiple sliding controllers, it is visible only problem when i try to show it under sliding controller it is not visible.
I hope you understand the problem.

**Comment by jjochen** [comment]
I have to admit I don't understand the problem.
I think without seeing some code I can't help.
