### ISSUE TITLE
Please allow single item with mini size

### ISSUE THREAD

**Issue by jahirfiquitiva** [jjochen/JJFloatingActionButton#151]
Mini size would be 40 for width and height, instead of the current 56.

Thanks

**Comment by jjochen** [comment]
JJFloatingActionButton is just an `UIView`. You can change it's size with layout constraints. 
I update the example project #152
Hope this solves your issue. Feel free to reopen it if it's still unclear.

**Comment by jahirfiquitiva** [comment]
@jjochen 
Great. Thanks 😀
