### ISSUE TITLE
Question: How to change the spacing between the titleLabel and circleView?

### ISSUE THREAD

**Issue by jahirfiquitiva** [jjochen/JJFloatingActionButton#154]
Hello

I am trying to make the space between the `titleLabel` and `circleView` bigger, but you're setting and hardcoding them internally in the `updateDynamicConstraints` function, and I cannot seem to change them.

So, what's the right way to change it? ... Can you add it as a property that one could edit?

Thanks

**Comment by jjochen** [comment]
True, this should be configurable but isn't. 
I'll probably find some time to implement that during the next couple of days.
