### ISSUE TITLE
Allow clicking labels

### ISSUE THREAD

**Issue by jahirfiquitiva** [jjochen/JJFloatingActionButton#158]
Hello

I was wondering if you could add an option to allow clicking on labels, and/or an option to call the click on a specific item of the fabs menu.

Thanks 😀

**Comment by jjochen** [comment]
@jahirfiquitiva Would this work for you? #166

**Comment by jahirfiquitiva** [comment]
@jjochen Probably not ... I'd expect the library to manage the click/tap in both the button and the label, or that there's a function like:
`button.triggerClick()` that would, literally, trigger the click action.

**Comment by jjochen** [comment]
I probably misunderstood. 
So, if you just want to trigger the tap action you could use a couple approaches.

Like for every other `UIControl` you could use: 
```
	actionButton.sendActions(for: .touchUpInside)
    actionItem.sendActions(for: .touchUpInside)
```
This would "mock" the tap.

You could also open the button and call the action of an action item directly:
```
	self.actionButton.open(animated: true) {
    	if let firstItem = self.actionButton.items.first {
        	firstItem.action?(firstItem)
    	}
	}
```

**Comment by jjochen** [comment]
Does this solve your issue? Feel free to reopen it if not.
