### ISSUE TITLE
First JJActionItem takes the tint color of the FAB, can this be configured? 

### ISSUE THREAD

**Issue by girishkoundinya** [jjochen/JJFloatingActionButton#160]
Really cool library :) 
I think this is by design, if there are multiple action items, the first action item image takes the tint color of the fab image. I think it might be better to make it configurable.

**Comment by jjochen** [comment]
Hey @girishkoundinya,

This should already be configurable. Check out the [example here](https://github.com/jjochen/JJFloatingActionButton/blob/76a476afda64baebd362af17939465c12523dc2d/Example/JJFloatingActionButton/ConfigurationExampleViewController.swift#L72).

If you need more help, feel free to reopen this ticket.
