### ISSUE TITLE
Cant get the buttons to display a plain image

### ISSUE THREAD

**Issue by lshannak** [jjochen/JJFloatingActionButton#162]
I am trying to display an image with its colors inside the button, but it always greens out the image if I dont set the item.buttonImageColor attribute.
I tried setting it to .clear color, but that makes the buttons disappear.
Can you please help!!

**Comment by jjochen** [comment]
You have to set the rendering mode to always original:
```
UIImage(named: "your_image")?.withRenderingMode(.alwaysOriginal)
```
(You can also configure this in your asset catalog)

Just reopen the ticket if you need more help.

**Comment by lshannak** [comment]
Thank you so much, it is working great!!!
