### ISSUE TITLE
 objective-c  Do not use pod  "Value for SWIFT_VERSION cannot be empty"

### ISSUE THREAD

**Issue by lotus-lotus** [jjochen/JJFloatingActionButton#168]
objective-c  Do not use pod, local import "Value for SWIFT_VERSION cannot be empty",
swfit language version change, The whole project error???

**Comment by jjochen** [comment]
Not exactly sure what you mean.

**Comment by lotus-lotus** [comment]
Do not use pod 'JJFloatingActionButton' , but download the souce in the project,  Add the souce(JJFloatingActionButton) file to my project .....

**Comment by lotus-lotus** [comment]
Because you have to "use_frameworks!",My other third party reported an error

**Comment by jjochen** [comment]
`use_frameworks!` is part of the cocoapods configuration. 
When you integrate it without using cocoapods this shouldn't be an issue.

**Comment by jjochen** [comment]
Still not sure what to do to reproduce this. 
Could you upload an example project?

**Comment by jjochen** [comment]
I will close this for now. Feel free to reopen it.
