### ISSUE TITLE
Button Action not called when inside UIContainerView

### ISSUE THREAD

**Issue by spedalilama** [jjochen/JJFloatingActionButton#176]
I have a UIViewController A with 2 UIContainerViews with embedded UIViewControllers A1 and A2.  When I add a JJFAB to the embedded UIVIewController A2 I see the button and it does highlight when selected, but the touch event doesn't get called.  If I instead add the JJFAB to the parent UIViewController A then it works as expected.  Any ideas on why the JJFAB in the embedded UIViewController A2 doesn't trigger the tap event?  For now, I'm just trying to get the same setup of the JJFAB found in ConfigurationExampleViewController.swift in the Example code to work.

**Comment by jjochen** [comment]
I couldn't reproduce this. 
I modified the example storyboard to contain an example with two container views. Check it out on the [support/container_views](https://github.com/jjochen/JJFloatingActionButton/tree/support/container_views) branch.
If this doesn't solve it for you, it would be helpful if you could attach an example project.

**Comment by spedalilama** [comment]
I was in the process of making a small example project to share and found the issue, the embedded viewController contained a scrollView with a tapGesture that was intercepting the touch event.  The other buttons/fields in this scrollView were working as expected which still confuses me, but I'm sure more research will turn up the reason.  Thanks for looking into this and thanks for sharing JJFAB!
