### ISSUE TITLE
How to Increase Title Label Height?

### ISSUE THREAD

**Issue by fcbmojtaba1995** [jjochen/JJFloatingActionButton#184]
Hi Thanks For This Library 
How to Increase Title Label Height? Please Help Me.Thanks

**Comment by jjochen** [comment]
Not exactly sure what you mean? The label height should increase automatically. 

Do you want to change the font size of the label?
You could use `configureDefaultItem` if you want to change all items, or edit the `item.titleLabel` of one specific item directly: 

```

        let actionButton = JJFloatingActionButton()

        actionButton.configureDefaultItem { item in
            item.titleLabel.font = .boldSystemFont(ofSize: 16)
            item.titleLabel.numberOfLines = 3
        }

        actionButton.addItem(title: "Heart", image: #imageLiteral(resourceName: "Favourite")) { item in
            Helper.showAlert(for: item)
        }

        let item = actionButton.addItem(title: "Like\nLike\nLike", image: #imageLiteral(resourceName: "Like")) { item in
            Helper.showAlert(for: item)
        }
        item.titleLabel.font = .boldSystemFont(ofSize: 14)

        actionButton.addItem(title: "Balloon", image: #imageLiteral(resourceName: "Baloon")) { item in
            Helper.showAlert(for: item)
        }

        actionButton.display(inViewController: self)
```

This would create a button like that: 
![screen shot 2019-01-17 at 11 12 56](https://user-images.githubusercontent.com/1793434/51311575-86eb1980-1a49-11e9-857b-8354c37cd490.png)

Hope this helps.
