### ISSUE TITLE
Button size changes with rotation/transition

### ISSUE THREAD

**Issue by jjochen** [jjochen/JJFloatingActionButton#191]
When the target image (including rotated image) is bigger then the button diameter the size of the button increases when opened.

**Comment by jjochen** [comment]
For now the safest way is to define the size of the button with autolayout. 

```
actionButton.translatesAutoresizingMaskIntoConstraints = false
actionButton.widthAnchor.constraint(equalToConstant: 65).isActive = true
actionButton.heightAnchor.constraint(equalToConstant: 65).isActive = true
```

**Comment by wdcurry** [comment]
dude, you are definitely "on it"! thank you. Awesome focused repo.

**Comment by MarcSteven** [comment]
> For now the safest way is to define the size of the button with autolayout.
> 
> ```
> actionButton.translatesAutoresizingMaskIntoConstraints = false
> actionButton.widthAnchor.constraint(equalToConstant: 65).isActive = true
> actionButton.heightAnchor.constraint(equalToConstant: 65).isActive = true
> ```

Yeah it makes sense ,give the actionButton the constraints(Width and height)))
