### ISSUE TITLE
Can't add only one item

### ISSUE THREAD

**Issue by MihailStoica1234** [jjochen/JJFloatingActionButton#202]
I'm not able to add only 1 item.

In your code example if I try to add only 1 item, it becomes automatically the main button. But I want to have the open button as well as the 1 item added by me

`let floatingButton: JJFloatingActionButton = JJFloatingActionButton(frame: .zero)`
      `  floatingButton.display(inView: superView)`
      `  floatingButton.buttonImage = UIImage(named: "CrossIcon")?.withRenderingMode(.alwaysTemplate)`
   ` let postItem = floatingButton.addItem()`
    `postItem.titleLabel.text = "General.Submenu.Post".localizable()`
   ` postItem.buttonImage = UIImage(named: "CrossIcon")?.withRenderingMode(.alwaysTemplate)`
    `postItem.buttonColor = TMColorConstants.darkGreenTagBackgroundColor.toColor`
    `postItem.action = { item in`
    `}`

**Comment by MihailStoica1234** [comment]
Solved it with `handleSingleActionDirectly`. Sorry

**Comment by jjochen** [comment]
Perfect
