### ISSUE TITLE
Add image size property to action items

### ISSUE THREAD

**Issue by ductranit** [jjochen/JJFloatingActionButton#203]
Hi, I wonder whether it can have a way to resize the menu icon in the button items? My action button & action items are quite large (130x130), but the icon size can't be changed although I use the large image. The icons look very small in the ipad.
Is there any way to do increaze their size by code? Some like:
```
actionButton.configureDefaultItem { item in
            item.size = CGSize()
```

**Comment by jjochen** [comment]
Hey, currently you can set `itemSizeRatio` on the action button to define the size of the items (see [here](https://github.com/jjochen/JJFloatingActionButton/blob/dfbaa82faf064a7706ddd5abb359244eaa606a91/Example/JJFloatingActionButton/ConfigurationExampleViewController.swift#L63))

If I remember correctly the image sizes are determined by its original size. If this doesn't work, something is wrong.

Could you post the image you are using, the size of the action button and the value of `itemSizeRatio` you are using? Then I could check what's happening.

**Comment by ductranit** [comment]
@jjochen  My code is
```
actionButton.itemSizeRatio = 0.95
actionButton.widthAnchor.constraint(equalToConstant: 130).isActive = true
actionButton.heightAnchor.constraint(equalToConstant: 130).isActive = true
```
My image is the pdf vector, it's small by default, but I though it could scale up?  
[menu-profiles.pdf](https://github.com/jjochen/JJFloatingActionButton/files/3211124/menu-profiles.pdf)
The item size can be changed according the action button, but not the icon https://gyazo.com/1c11cfab03b464a1aafb8caa571f4d75

**Comment by jjochen** [comment]
Yes, that's it. I think the intrinsic content size of the image view is used which uses the original size of the image. 
Also the pdf appears to contain a lot of whitespace around the actual icon. Maybe removing that is already enough?

On the other hand it's probably a good idea to be able to fix the image size somehow independent of the actual image size.

**Comment by jjochen** [comment]
For now you could use something like this:

```

**Comment by ductranit** [comment]
@jjochen Thanks for you help. But how can I remove the existing constraints? The constraints code is in the library.
I try something like this: 
```
actionButton.configureDefaultItem { item in
            //let imageSizeMuliplier = CGFloat(1 / sqrt(2))
            NSLayoutConstraint.deactivate(item.imageView.constraints)
            item.imageView.widthAnchor.constraint(equalTo: item.circleView.widthAnchor, multiplier: 0.9).isActive = true
            item.imageView.heightAnchor.constraint(equalTo: item.circleView.heightAnchor, multiplier: 0.9).isActive = true
        }
``` 
And the action items are disappeared cause it conflicts with the existing ones as you said

**Comment by ductranit** [comment]
Btw, I remove the whitespace around the actual icon, then scale up image and it works. Hope you can add a feature to resize later. Thanks

**Comment by jjochen** [comment]
@ductranit That's good to hear! I think that's actually the best way to go.

I might add an image size property once I have a bit more time at hand.
