### ISSUE TITLE
Delegate methods on action button not being called

### ISSUE THREAD

**Issue by jakelindsay** [jjochen/JJFloatingActionButton#205]
I added the delegate methods to my project following the Github example, but they are not being triggered.

**Comment by jjochen** [comment]
Hey, sorry to hear that. Could you upload some sample code.

**Comment by texyz** [comment]
actionButton.addItem(image: #imageLiteral(resourceName: "notificationImage")) { item in
            Helper.showAlert(for: item)
        }
        
        actionButton.addItem(image: #imageLiteral(resourceName: "rubiesLogo")) { item in
            Helper.showAlert(for: item)
        }
        
        actionButton.addItem(image: #imageLiteral(resourceName: "passwordIcon")) { item in
            Helper.showAlert(for: item)
        }
        
        actionButton.addItem(image: #imageLiteral(resourceName: "descriptionIcon")) { item in
            Helper.showAlert(for: item)
        }


Use of unresolved identifier 'Helper'

Please kindly help fix

**Comment by jjochen** [comment]
This is in you own code, right? `Helper` is a class of the example app.
Replace above code with

        actionButton.addItem(image: #imageLiteral(resourceName: "notificationImage")) { item in
            // item was tapped
        }
        
        actionButton.addItem(image: #imageLiteral(resourceName: "rubiesLogo")) { item in
            // item was tapped
        }
        
        actionButton.addItem(image: #imageLiteral(resourceName: "passwordIcon")) { item in
            // item was tapped
        }
        
        actionButton.addItem(image: #imageLiteral(resourceName: "descriptionIcon")) { item in
            // item was tapped
        }

**Comment by jjochen** [comment]
@jakelindsay I will close this for now as there has not been any activity regarding the original issue.

Feel free to reopen if you need more help.

**Comment by jakelindsay** [comment]
Sorry, just saw this. Just had to add the action button delegate = self in the viewdidload and it started working.
