### ISSUE TITLE
Change action button image when tapped

### ISSUE THREAD

**Issue by jakelindsay** [jjochen/JJFloatingActionButton#206]
I see this might already be possible from issue #35, but there isn't a code sample for it. I want to have one image for when the button menu is closed and a different one when the menu is open. I have tried changing the image in the delegate methods for open and close and in the closures for open and close, but it doesn't seem to work. Is this possible? If so, can you provide the code to do it?

This is what I have tried.

        actionButton.open(animated: true, completion: {

            self.playBackgroundSound(soundString: "button-tap")
            actionButton.buttonImage = UIImage(named: "clapboard-open")

        })

        actionButton.close(animated: true, completion: {

            self.playBackgroundSound(soundString: "button-tap")
            actionButton.buttonImage = UIImage(named: "clapboard-closed")

        })

And this.

    func floatingActionButtonWillOpen(_ button: JJFloatingActionButton) {
        print("Action button will open: \(button.state)")
        self.playBackgroundSound(soundString: "button-tap")
        actionButton.buttonImage = UIImage(named: "clapboard-open")
    }
    
    func floatingActionButtonDidOpen(_ button: JJFloatingActionButton) {
        print("Action button did open: \(button.state)")
    }
    
    func floatingActionButtonWillClose(_ button: JJFloatingActionButton) {
        print("Action button will close: \(button.state)")
        self.playBackgroundSound(soundString: "button-tap")
        actionButton.buttonImage = UIImage(named: "clapboard-closed")
    }
    
    func floatingActionButtonDidClose(_ button: JJFloatingActionButton) {
        print("Action button did close: \(button.state)")
    }

**Comment by jjochen** [comment]
Check the example project for an example: 

https://github.com/jjochen/JJFloatingActionButton/blob/dfbaa82faf064a7706ddd5abb359244eaa606a91/Example/JJFloatingActionButton/ConfigurationExampleViewController.swift#L55

Hope that's what you are looking for.

**Comment by jakelindsay** [comment]
That worked. Thanks for the quick response.

Looks like the image transition was conflicting with the image rotation. When I commented out the rotation, the image change worked. Is there a way to do both?
