### ISSUE TITLE
How do I change the image size of the buttons?

### ISSUE THREAD

**Issue by yejunantonylee** [jjochen/JJFloatingActionButton#207]
I am trying to figure out how I can change the actual size of the image **AND** remove the white and green border on all buttons (for both main and action button items).

<img width="98" alt="Screen Shot 2019-08-25 at 3 03 40 PM" src="https://user-images.githubusercontent.com/46239175/63656512-a36ed300-c749-11e9-96d4-7371a94887a5.png">
<img width="871" alt="Screen Shot 2019-08-25 at 3 06 33 PM" src="https://user-images.githubusercontent.com/46239175/63656538-03fe1000-c74a-11e9-826c-945ee5ab2116.png">

This is what I have, but I want to get rid of the white and green borders (I am not sure if it is the border or just the background button View due to small image size) **AND** resize the images. The image asset size is 96 x 96 pixels, which shouldn't be the cause of this issue.

Thank you in advance!

**Comment by jjochen** [comment]
I guess this is currently not possible, but I want to make that configurable.

**Comment by jjochen** [comment]
Related to #203
