### ISSUE TITLE
Leave action buttons visible

### ISSUE THREAD

**Issue by yu-t** [jjochen/JJFloatingActionButton#221]
Hi, currently when I click on some action button - all action buttons become hidden. Is it possible not to hide action buttons in that case, so I can close floating action button myself? Thanks!

**Comment by jjochen** [comment]
Hey Yuliya, this is currently not possible.
Making this configurable would probably make sense though.

**Comment by Bradeskojest** [comment]
I was about to ask the same question. Is there a timeline for 2.2.0? Thank you!
