### ISSUE TITLE
Need to remove animation while closing items

### ISSUE THREAD

**Issue by sohail-niazi** [jjochen/JJFloatingActionButton#223]
I need to remove animation while closing items, because when I remove actionbutton from view, items kept remain there for always. I cannot wait to have all items hidden with animation.

Kindly, provide solution for this and 1 more, if we can remove items from actionButton

**Comment by jjochen** [comment]
There is now a [pull request](https://github.com/jjochen/JJFloatingActionButton/pull/238) for the first part of this issue. 
I created a [new issue](https://github.com/jjochen/JJFloatingActionButton/issues/239) for the second part.

**Comment by jjochen** [comment]
@sohail-niazi Btw. you can easily "remove" an item by setting it to "hidden":
```
let item = actionButton.addItem(title: "go for it!", image: UIImage(named: "image.png")) { item in
    // do something
}

item.isHidden = true
```

Setting `isHidden` to `false` would make it appear again.

**Comment by jjochen** [comment]
And it should also be ok to just use `remove(at:)` to remove an item:
```
if let index = items.firstIndex(of: item) {
    actionButton.items.remove(at: index)
}
```
