### ISSUE TITLE
Full circle image in actionitems

### ISSUE THREAD

**Issue by kgreggersen** [jjochen/JJFloatingActionButton#237]
I'm pretty new to github and iOS development, so I hope I am asking in the right place and the right way...? First thanks for the Floating Button and your effort!
My question: I'd like to put a small picture into the imageView of the actionItem and want the image to fill the whole button / circle shape. when I adjust the image size, the image is displayed as a square and calling layer.cornerRadius on imageView and or item doesn't work. Is it possible to do and do you have any suggestions?
Thanks.

**Comment by kgreggersen** [comment]
got it to work.
changed the code where I configure the actionItems and added the following to each action item:
item.imageView.layer.masksToBounds = true
item.imageView.layer.cornerRadius = 20

didn't work until I set masksToBounds to true

**Comment by jjochen** [comment]
Awesome! Good to hear.
