### ISSUE TITLE
I can‘t run the example

### ISSUE THREAD

**Issue by iOSstudyPerson** [jjochen/JJFloatingActionButton#256]
I want to run the example project, But I failed when I executed the pod update command.
And I don't know how to download this version of public_suffix-2.0.5.
can you help me? Thanks

**Comment by jjochen** [comment]
@iOSstudyPerson Did #261 resolve your problem?

**Comment by jjochen** [comment]
btw. why did you try to do an `pod update`?

The easies way to run the example is probably by running 
```
pod try JJFloatingActionButton
```

**Comment by jjochen** [comment]
I will close this for now. Feel free to reopen it if the issue is not resolved.
