### ISSUE TITLE
Press-and-hold ability

### ISSUE THREAD

**Issue by austboston** [jjochen/JJFloatingActionButton#266]
This is awesome, thanks for sharing! Is there someway to have the button perform an action when simply tapped, but open the menu when it is tapped and held? Similar to the floating button on Twitter. Any ideas? Thanks! Austin Blake

**Comment by jjochen** [comment]
you could remove the tap action
```
actionButton.removeTarget(actionButton, action: nil, for: .touchUpInside)
```
and handle the opening and closing of the button yourself.
