### ISSUE TITLE
How change default green color to system blue?

### ISSUE THREAD

**Issue by rayastar** [jjochen/JJFloatingActionButton#267]
How change default green color to system blue? code below doesn't work:

let imageView = UIImage(named: "random-20")
        imageView?.withTintColor(UIColor.systemBlue)

        
        actionButton.addItem(title: "title", image: imageView!.withRenderingMode(.alwaysTemplate)) { item in
          // do something
        }

**Comment by jjochen** [comment]
You can set `buttonColor` like so
```
actionButton.buttonColor = .red
```

See [here for a full example](https://github.com/jjochen/JJFloatingActionButton/blob/60fcde6d01aa33598753214b9438c192f2074900/Example/JJFloatingActionButton/ConfigurationExampleViewController.swift#L53).
