### ISSUE TITLE
Circular FAB is in the centre of screen

### ISSUE THREAD

**Issue by SalilLuley** [jjochen/JJFloatingActionButton#268]
Hi, I want to open fab in circular pattern. Problem I am facing here is my FAB is in the centre of screen on right side. Now I want to change the rotation but I guess I am doing something wrong and it is not helping.

Attaching an  image for reference.

![Output](https://user-images.githubusercontent.com/24896386/85196856-af400d00-b2fa-11ea-972c-846f622d790b.png)

Thanks in advance.

**Comment by jjochen** [comment]
You would need to define a custom `JJItemAnimationConfiguration` similar to the [`DownwardsExampleViewController`](https://github.com/jjochen/JJFloatingActionButton/blob/master/Example/JJFloatingActionButton/DownwardsExampleViewController.swift#L34-L44) in the example app.

Tell me if you need more help.

**Comment by SalilLuley** [comment]
Thank you it worked

For reference to other people

`internal class DownwardsExampleViewController: UIViewController {
    fileprivate let actionButton = JJFloatingActionButton()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let configuration = JJItemAnimationConfiguration()
        configuration.itemLayout = JJItemLayout { items, actionButton in
            var count = 0
            var previousItem: JJActionItem?
            for item in items {
                let previousView = previousItem ?? actionButton
                if count == 0 {
                    item.leadingAnchor.constraint(equalTo: previousView.leadingAnchor, constant: -150).isActive = true
                    item.topAnchor.constraint(equalTo: previousView.topAnchor, constant: -60).isActive = true
                } else if count == 1 {
                    item.leadingAnchor.constraint(equalTo: previousView.leadingAnchor, constant: -60).isActive = true
                    item.topAnchor.constraint(equalTo: previousView.topAnchor, constant: 70).isActive = true

                }  else if count == 2 {
                    item.leadingAnchor.constraint(equalTo: previousView.leadingAnchor, constant: 50).isActive = true
                    item.topAnchor.constraint(equalTo: previousView.topAnchor, constant: 70).isActive = true
                }
                count += 1
                previousItem = item
            }
        }
        actionButton.itemAnimationConfiguration = configuration
        actionButton.addItem(title: "Heart", image: #imageLiteral(resourceName: "Favourite")) { item in
            Helper.showAlert(for: item)
        }
        
        actionButton.addItem(title: "Like", image: #imageLiteral(resourceName: "Like")) { item in
            Helper.showAlert(for: item)
        }
        
        actionButton.addItem(title: "Balloon", image: #imageLiteral(resourceName: "Baloon")) { item in
            Helper.showAlert(for: item)
        }
        view.addSubview(actionButton)
        
        actionButton.translatesAutoresizingMaskIntoConstraints = false
        if #available(iOS 11.0, *) {
            actionButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: -16).isActive = true
            actionButton.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 100).isActive = true
        } else {
            actionButton.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -16).isActive = true
            actionButton.topAnchor.constraint(equalTo: topLayoutGuide.bottomAnchor, constant: 16).isActive = true
            actionButton.widthAnchor.constraint(equalToConstant: 60).isActive = true
            actionButton.heightAnchor.constraint(equalToConstant: 60).isActive = true
        }
    }
}`

![Simulator Screen Shot - iPhone 11 - 2020-06-26 at 21 45 29](https://user-images.githubusercontent.com/24896386/85878469-5db1e980-b7f6-11ea-9302-28b932ae1ee3.png)
