### ISSUE TITLE
How can I make this button Horizontal?

### ISSUE THREAD

**Issue by vignesh-lesoft** [jjochen/JJFloatingActionButton#271]

**Comment by jjochen** [comment]
You have to create a new `JJItemAnimationConfiguration`. 
You can check the [`DownwardsExampleViewController`](https://github.com/jjochen/JJFloatingActionButton/blob/master/Example/JJFloatingActionButton/DownwardsExampleViewController.swift) as an example.

**Comment by vignesh-lesoft** [comment]
Working!!

Thanks for your active support
