### ISSUE TITLE
Adding Badge to Floating Action Button

### ISSUE THREAD

**Issue by Free-tek** [jjochen/JJFloatingActionButton#272]
We might need to add a badge to the floating action button

**Comment by jjochen** [comment]
Not exactly sure what you mean. 

Btw. the action button and all its action items are UIViews, so you can ad subviews as to any other view.

**Comment by Free-tek** [comment]
![WhatsApp Image 2020-11-21 at 2 41 55 PM](https://user-images.githubusercontent.com/40810247/99878774-f7e05700-2c07-11eb-9fed-2259b43e5d8a.jpeg)

Can you see the two that is the total count for orders on the floating action button, that is what I meant by a badge

**Comment by Free-tek** [comment]
i had to build this from scratch, it would have been a nice to have
