### ISSUE TITLE
Easiest way for Downward CircularSlideIn?

### ISSUE THREAD

**Issue by shadowstriker15** [jjochen/JJFloatingActionButton#274]
Hello, I was wondering if I could get some help on using the CircularSlideIn animation but for the items to appear below the FAB? Essentially, rotating the displayed items by 180. Thanks!

**Comment by jjochen** [comment]
[Check here](https://github.com/jjochen/JJFloatingActionButton/blob/7a8b6d3fef76fd55079c896cac24fde66cd1afa0/Example/JJFloatingActionButton/ConfigurationExampleViewController.swift#L60-L76) how to create your own custom layout. Hope this helps.

**Comment by jjochen** [comment]
Closing this for now.
