### ISSUE TITLE
Circular configuration is not customisable angles are hardcoded

### ISSUE THREAD

**Issue by amodkanthe** [jjochen/JJFloatingActionButton#276]
Circular configuration is not customisable angles are hardcoded unable to achieve something like below start and end angle required.

<img width="349" alt="Screenshot 2020-12-29 at 2 14 30 PM" src="https://user-images.githubusercontent.com/5066441/103271520-7a66ee00-49e0-11eb-93f8-02a73662011e.png">

**Comment by Snow-Tech** [comment]
Hello @jjochen , I would know if is possible, or if you know any workaround that can be used? Thank you

**Comment by MarcSteven** [comment]
@Snow-Tech  perhaps  the library has paused to maintain

**Comment by valenwalker** [comment]
Hi @amodkanthe, could you achieve this?

**Comment by jjochen** [comment]
Sorry for the long wait. One way to achieve this is create your custom layout. [Check here](https://github.com/jjochen/JJFloatingActionButton/blob/7a8b6d3fef76fd55079c896cac24fde66cd1afa0/Example/JJFloatingActionButton/ConfigurationExampleViewController.swift#L60-L76) how to do that.
