### ISSUE TITLE
Pop two lines of buttons on both horizontal and vertical directions.

### ISSUE THREAD

**Issue by internalG** [jjochen/JJFloatingActionButton#281]
## Describe the solution you'd like.
Is there a sample code for that? Thanks.

**Comment by jjochen** [comment]
There is no example for exactly that case but you can [check here](https://github.com/jjochen/JJFloatingActionButton/blob/7a8b6d3fef76fd55079c896cac24fde66cd1afa0/Example/JJFloatingActionButton/ConfigurationExampleViewController.swift#L60-L76) how to crate your custom layout.

**Comment by jjochen** [comment]
Hope this helps. Closing this for now.
