### ISSUE TITLE
Close automatically

### ISSUE THREAD

**Issue by oxnnj** [jjochen/JJFloatingActionButton#282]
I am displaying the action button on view controller which is inside the UITabViewController, I want to close the action button when the other view controller is pressed in tabbar. Does current version supports this?

**Comment by jjochen** [comment]
It is possible to call [`close`](https://jjochen.github.io/JJFloatingActionButton/Classes/JJFloatingActionButton.html#/c:@CM@JJFloatingActionButton@objc(cs)JJFloatingActionButton(im)closeWithAnimated:completion:) on the action button directly. 
So you could use this inside the [`UITabViewControllerDelegate`](https://developer.apple.com/documentation/uikit/uitabbarcontrollerdelegate/1621173-tabbarcontroller?language=objc).
Hope this helps.

**Comment by jjochen** [comment]
I'll close this for now.
