### ISSUE TITLE
Button image not appearing on button

### ISSUE THREAD

**Issue by ahmedayoub95** [jjochen/JJFloatingActionButton#284]
## Describe the bug

actionButton.buttonImage does not appear the image on button.

## To reproduce

1. actionButton.buttonImage = UIImage(named: "chat_float_icon.png")

## Environment

- JJFloatingActionButton version:  2.5.0
- iOS version: 16.2
- Xcode version: 14.2 (14C18)
- Is the issue you're experiencing reproducible in the example app? 
- ...

**Comment by jjochen** [comment]
Do you have a reproducible example. There is not a lot to go on.

**Comment by jjochen** [comment]
Closing this for now
