### ISSUE TITLE
'JJFloatingActionButtonDelegate' is not a member type of class 'JJFloatingActionButton.JJFloatingActionButton'

### ISSUE THREAD

**Issue by RedaBenlakehal** [jjochen/JJFloatingActionButton#285]
After installing Xcode 15, I encountered the following error:

"'JJFloatingActionButtonDelegate' is not a member type of the class 'JJFloatingActionButton.JJFloatingActionButton.'
'JJFloatingActionButton' is not a member type of the class 'JJFloatingActionButton.JJFloatingActionButton.'

Has anyone else experienced this error?"

**Comment by jjochen** [comment]
@RedaBenlakehal Could you check if this is still happening with the current master branch?

**Comment by jjochen** [comment]
Hope this was fixed with 3.0.0. Closing this for now.
